/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-07 09:52:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<Style>\n");
      out.write("#success_message{ display: none;}\n");
      out.write("</style>\n");
      out.write("<Script>\n");
      out.write(" $(document).ready(function() {\n");
      out.write("    $('#contact_form').bootstrapValidator({\n");
      out.write("        // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later\n");
      out.write("        feedbackIcons: {\n");
      out.write("            valid: 'glyphicon glyphicon-ok',\n");
      out.write("            invalid: 'glyphicon glyphicon-remove',\n");
      out.write("            validating: 'glyphicon glyphicon-refresh'\n");
      out.write("        },\n");
      out.write("        fields: {\n");
      out.write("            first_name: {\n");
      out.write("                validators: {\n");
      out.write("                        stringLength: {\n");
      out.write("                        min: 2,\n");
      out.write("                    },\n");
      out.write("                        notEmpty: {\n");
      out.write("                        message: 'Please enter your First Name'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("             last_name: {\n");
      out.write("                validators: {\n");
      out.write("                     stringLength: {\n");
      out.write("                        min: 2,\n");
      out.write("                    },\n");
      out.write("                    notEmpty: {\n");
      out.write("                        message: 'Please enter your Last Name'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("\t\t\t user_name: {\n");
      out.write("                validators: {\n");
      out.write("                     stringLength: {\n");
      out.write("                        min: 8,\n");
      out.write("                    },\n");
      out.write("                    notEmpty: {\n");
      out.write("                        message: 'Please enter your Username'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("\t\t\t user_password: {\n");
      out.write("                validators: {\n");
      out.write("                     stringLength: {\n");
      out.write("                        min: 8,\n");
      out.write("                    },\n");
      out.write("                    notEmpty: {\n");
      out.write("                        message: 'Please enter your Password'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("\t\t\tconfirm_password: {\n");
      out.write("                validators: {\n");
      out.write("                     stringLength: {\n");
      out.write("                        min: 8,\n");
      out.write("                    },\n");
      out.write("                    notEmpty: {\n");
      out.write("                        message: 'Please confirm your Password'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            email: {\n");
      out.write("                validators: {\n");
      out.write("                    notEmpty: {\n");
      out.write("                        message: 'Please enter your Email Address'\n");
      out.write("                    },\n");
      out.write("                    emailAddress: {\n");
      out.write("                        message: 'Please enter a valid Email Address'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            contact_no: {\n");
      out.write("                validators: {\n");
      out.write("                  stringLength: {\n");
      out.write("                        min: 12, \n");
      out.write("                        max: 12,\n");
      out.write("                    notEmpty: {\n");
      out.write("                        message: 'Please enter your Contact No.'\n");
      out.write("                     }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("\t\t\t department: {\n");
      out.write("                validators: {\n");
      out.write("                    notEmpty: {\n");
      out.write("                        message: 'Please select your Department/Office'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        })\n");
      out.write("        .on('success.form.bv', function(e) {\n");
      out.write("            $('#success_message').slideDown({ opacity: \"show\" }, \"slow\") // Do something ...\n");
      out.write("                $('#contact_form').data('bootstrapValidator').resetForm();\n");
      out.write("\n");
      out.write("            // Prevent form submission\n");
      out.write("            e.preventDefault();\n");
      out.write("\n");
      out.write("            // Get the form instance\n");
      out.write("            var $form = $(e.target);\n");
      out.write("\n");
      out.write("            // Get the BootstrapValidator instance\n");
      out.write("            var bv = $form.data('bootstrapValidator');\n");
      out.write("\n");
      out.write("            // Use Ajax to submit form data\n");
      out.write("            $.post($form.attr('action'), $form.serialize(), function(result) {\n");
      out.write("                console.log(result);\n");
      out.write("            }, 'json');\n");
      out.write("        });\n");
      out.write("});\n");
      out.write("</Script>\n");
      out.write("<body>\n");
      out.write(" <div class=\"container\">\n");
      out.write("\n");
      out.write("    <form class=\"well form-horizontal\" action=\" \" method=\"post\"  id=\"contact_form\">\n");
      out.write("<fieldset>\n");
      out.write("\n");
      out.write("<!-- Form Name -->\n");
      out.write("<center>\n");
      out.write("  <div class=\"form-group\"> \n");
      out.write("<legend><center><h2><b>Registration Form</b></h2></center></legend><br>\n");
      out.write("\n");
      out.write("<!-- Text input-->\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("  <label class=\"col-md-4 control-label\">Username</label>  \n");
      out.write("  <div class=\"col-md-4 inputGroupContainer\">\n");
      out.write("  <div class=\"input-group\">\n");
      out.write("  <span class=\"input-group-addon\">< class=\"glyphicon glyphicon-user\"></i></span>\n");
      out.write("  <input  name=\"user_name\" placeholder=\"Username\" class=\"form-control\"  type=\"text\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Text input-->\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("  <label class=\"col-md-8control-label\" >Password</label> \n");
      out.write("    <div class=\"col-md-4 inputGroupContainer\">\n");
      out.write("    <div class=\"input-group\">\n");
      out.write("  <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\n");
      out.write("  <input name=\"user_password\" placeholder=\"Password\" class=\"form-control\"  type=\"password\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Text input-->\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("  <label class=\"col-md-4 control-label\" >Confirm Password</label> \n");
      out.write("    <div class=\"col-md-4 inputGroupContainer\">\n");
      out.write("    <div class=\"input-group\">\n");
      out.write("  <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\n");
      out.write("  <input name=\"confirm_password\" placeholder=\"Confirm Password\" class=\"form-control\"  type=\"password\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Text input-->\n");
      out.write("       <div class=\"form-group\">\n");
      out.write("  <label class=\"col-md-4 control-label\">E-Mail</label>  \n");
      out.write("    <div class=\"col-md-4 inputGroupContainer\">\n");
      out.write("    <div class=\"input-group\">\n");
      out.write("        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\n");
      out.write("  <input name=\"email\" placeholder=\"E-Mail Address\" class=\"form-control\"  type=\"text\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Text input-->\n");
      out.write("       \n");
      out.write("<div class=\"form-group\">\n");
      out.write("  <label class=\"col-md-4 control-label\">Contact No.</label>  \n");
      out.write("    <div class=\"col-md-4 inputGroupContainer\">\n");
      out.write("    <div class=\"input-group\">\n");
      out.write("        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-earphone\"></i></span>\n");
      out.write("  <input name=\"contact_no\" placeholder=\"(639)\" class=\"form-control\" type=\"text\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Select Basic -->\n");
      out.write("\n");
      out.write("<!-- Success message -->\n");
      out.write("<div class=\"alert alert-success\" role=\"alert\" id=\"success_message\">Success <i class=\"glyphicon glyphicon-thumbs-up\"></i> Success!.</div>\n");
      out.write("\n");
      out.write("<!-- Button -->\n");
      out.write("<div class=\"form-group\">\n");
      out.write("  <label class=\"col-md-4 control-label\"></label>\n");
      out.write("  <div class=\"col-md-4\"><br>\n");
      out.write("  <button type=\"submit\" class=\"btn btn-warning\" ><span class=\"glyphicon glyphicon-send\"></span></button>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</fieldset>\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("    </div><!-- /.container -->\n");
      out.write("</body>\n");
      out.write("</center>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
